version: 3.0
services:
  backend:
    image: ubuntu:latest
    container_name: softy-pinko-back-end-task4
    build:
      context: ./back-end
      dockerfile: Dockerfile
      # target: runner
    ports:
     - 5252:5252
    restart: always
    
  frontend:
    image: nginx:latest
    container_name: softy-pinko-front-end-task4
    build:
      context: ./front-end
      dockerfile: Dockerfile
    depends_on: 
        - backend
    # Nginx default port is 80
    ports:
      - 9000:9000
    pull_policy: never
    restart: always